### PR TITLE
Add details for Anurag's talk

### PR DESCRIPTION
**Pull request by lazyoracle**

### CODE REVIEW

**Review by nathanshammah — APPROVED** [review]
Thank you @lazyoracle!

**Comment by lazyoracle** [comment]
Hey, thanks for merging this. I just realised that I have missed out on also updating the `index.md` besides the `README.md`. Sorry about that 🤦🏾‍♂️ 
Will you just update the `index.md` by copying over the text from the `README.md` on your end?

**Comment by nathanshammah** [comment]
What if we just show the readme to we avoid duplication?

**Comment by lazyoracle** [comment]
Yes that is the better solution imho, prevents duplication of efforts. Would also mean its easier to maintain for you folks.

**Pull request merged**
